# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Set up Swift environment
    - name: Set up Swift
      run: |
        swift --version

    # Step 3: Build the project
    - name: Build project
      run: swift build -v

    # Step 4: Run XCTest tests
    - name: Run XCTest tests
      run: swift test -v

    # Step 5: Run SwiftTest (if applicable)
    - name: Run SwiftTest
      # Make sure you add proper configuration for SwiftActions
      uses: SwiftActions/SwiftTest@0.2

    # Step 6: Run Super-Linter
    - name: Run Super-Linter
      uses: super-linter/super-linter@v7.1.0
      env:
        VALIDATE_ALL_CODEBASE: true
        DEFAULT_BRANCH: main
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Step 7: Run SwiftLint (optional but recommended for Swift code linting)
    - name: Run SwiftLint
      run: |
        if ! which swiftlint > /dev/null; then
          brew install swiftlint
        fi
        swiftlint
