# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Set up Xcode
      run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

    - name: Build the project
      run: xcodebuild -scheme "miniProject-seniorDesign" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 16 Pro' build | xcpretty

    - name: Run Unit Tests
      run: xcodebuild test -scheme "miniProject-seniorDesign" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 16 Pro' | xcpretty
